server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    com.xufei: info
    org.springframework: warn
  config: classpath:logback-plus.xml

spring:
  application:
    name: mis-vue-plus
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 400MB
  devtools:
    restart:
      enabled: true
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml